name: create-pull-request

on: 
  workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: git checkout -b $(npm show maplibre-gl version)
    - run: touch hello.txt
    - run: git config --global user.email "mail@example.com"
    - run: git config --global user.name "GitHub Action"
    - run: git add hello.txt
    - run: git commit -m "say hi"
    - run: git push --set-upstream origin $(npm show maplibre-gl version)
    - run: gh pr create --base main --fill
