name: create-pull-request

on: 
  workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
      git checkout -b test
      touch hello.txt
      git add hello.txt
      git commit -m "say hi"
      git push 
